collector_url: "http://localhost:4318"
#collector_url: "http://192.168.0.81:4318" # 현정
#collector_url: "http://192.168.0.158:4318" # 다영
#collector_url: "http://192.168.0.42:4318" # 다영

# 현재 go routine 하나 당 세션 ID 하나로 생성됨. (세션아이디 주기적 갱신 아직 없음)
go_routine_count: 300
# userID 가지 수
user_count: 2000
generate:
  # use_dynamic_interval
  # - false: 트레이스 생성시 처음 정해진 주기로 동일한 간격 생성
  # --- trace_interval_min_seconds ~ trace_interval_max_seconds 사이 값으로 랜덤으로 지정되지만 한 번 지정되면 지정된 간격으로 주기적으로 생성
  # -true: 트레이스 생성시 매번 생성마다 불규칙한 간격으로 생성
  # --- trace_interval_min_seconds ~ trace_interval_max_seconds 사이 값으로 트레이스 생성마다 매번 랜덤 간격
  use_dynamic_interval: true
  min_trace_interval_second: 5
  max_trace_interval_second: 100
  max_child_span_count: 8
  max_span_duration_millisecond: 5432
  # session id refresh option
  use_session_id_refresh: true
  min_session_id_refresh_interval_minute: 30
  max_session_id_refresh_interval_minute: 180

services:
  # ios
  - namespace: "foo namespace"
    name: "ios1"
    version: "1.0.0"
    key: "E-ldOBKcGCSJ0W-KCTT6da6haJselZwnf4VQOGS-mpct5-kLwlsReKeaN8MADA.hZLa3MmavaVO7FJkHCdeoQ"
    type: "ios"
#  - namespace: "foo namespace"
#    name: "ios1"
#    version: "1.0.1"
#    key: "service-key"
#    type: "ios"
#  - namespace: "foo namespace"
#    name: "ios1"
#    version: "1.0.2"
#    key: "service-key"
#    type: "ios"
#  - namespace: "foo namespace"
#    name: "ios2"
#    version: "1.0.11"
#    key: "service-key"
#    type: "ios"
  # android
#  - namespace: "foo namespace"
#    name: "and1"
#    version: "1.3.5"
#    key: "service-key"
#    type: "android"
  - namespace: "foo namespace"
    name: "and1"
    version: "1.0.0"
    key: "ElJJwfCnMkcJvUnzspexarKL2auKLycZEM6xoDr8yiQJkqzwHbOCwUk3GyKpvA.KkjYP0xozjOrkbJwCQ7QVg"
    type: "android"
#  - namespace: "foo namespace"
#    name: "and2"
#    version: "2.1.1"
#    key: "service-key"
#    type: "android"
#  - namespace: "foo namespace"
#    name: "and3"
#    version: "1.0.4"
#    key: "service-key"
#    type: "android"
##   web
#  - namespace: "foo namespace"
#    name: "web1"
#    version: "1.0.0"
#    key: "6uL46e_8SLokrBBQpxrSkAuuji2uFJQ7NIqwpDKWkj9TbNql2wxz-1Zxm-qKLw.o0SBcISsLnXSJetpE5ACqw"
#    type: "web"
#  - namespace: "foo namespace"
#    name: "web1"
#    version: "3.0.12"
#    key: "service-key"
#    type: "web"
#  - namespace: "foo namespace"
#    name: "web2"
#    version: "3.2.1"
#    key: "service-key"
#    type: "web"
resource_attribute:
  os_name:
    android:
      - "android"
    ios:
      - "iOS"
    web:
#      - "Android"
#      - "iOS"
#      - "Windows"
#      - "macOS"
  os_version:
    android:
      - "14"
      - "13"
      - "12"
      - "11"
      - "10"
    ios:
      - "18.0"
      - "17.6"
      - "17.5.1"
      - "17.4"
      - "16.7"
      - "15.8.2"
    web:
  device_model_identifier:
    android:
      - "SM-S928N" # Galaxy S24 Ultra
      - "SM-S918N" # Galaxy S23 Ultra
      - "SM-G998B" # Galaxy S21 Ultra
      - "SM-F946N" # Galaxy Z Fold 5
      - "SM-F731N" # Galaxy Z Flip 5
      - "SM-A546S" # Galaxy A54
      - "SM-T870"  # Galaxy Tab S7
      - "LM-V600N" # LG V60 ThinQ
      - "pixel 8 pro"
      - "pixel 7"
      - "pixel 6a"
      - "2201116SG" # Xiaomi Poco X4 Pro
      - "23049PCD8G" # Xiaomi Poco F5
    ios:
      - "iPhone16,2" # iPhone 15 Pro Max
      - "iPhone15,2" # iPhone 14 Pro
      - "iPhone14,5" # iPhone 13
      - "iPhone13,4" # iPhone 12 Pro Max
      - "iPhone12,1" # iPhone 11
      - "iPhone14,6" # iPhone SE (3rd generation)
      - "iPad14,6"   # iPad Pro 12.9-inch (6th generation)
      - "iPad13,17"  # iPad Air (5th generation)
      - "iPad8,1"    # iPad Pro 11-inch (1st generation)
    web:

span_attribute:
  screen_names:
    android:
      - "MainActivity"
      - "and-test-screen-name-1"
      - "and-test-screen-name-2"
      - "and-test-screen-name-3"
      - "and-test-screen-name-4"
      - "and-test-screen-name-5"
      - "and-test-screen-name-6"
    ios:
      - "ios-test-screen-name-1"
      - "ios-test-screen-name-2"
      - "ios-test-screen-name-3"
      - "ios-test-screen-name-4"
      - "ios-test-screen-name-5"
      - "ios-test-screen-name-6"
      - "ios-test-screen-name-7"
    web:
      - "web-test-screen-name-1"
      - "web-test-screen-name-2"
      - "web-test-screen-name-3"
  http_urls:
    - "https://www.google.com/"
    - "https://www.google.com/search?q=otlp+exporter&oq=otlp"
    - "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    - "https://www.youtube.com/feed/subscriptions"
    - "https://www.amazon.com/s?k=laptop&ref=nb_sb_noss"
    - "https://www.amazon.com/gp/product/B08N5T6CZ6/"
    - "https://en.wikipedia.org/wiki/OpenTelemetry"
    - "https://en.wikipedia.org/wiki/Main_Page"
    - "https://twitter.com/home"
    - "https://twitter.com/explore"
    - "https://www.instagram.com/p/Cyzqr0oyRk_/"
    - "https://www.linkedin.com/feed/"
    - "https://www.microsoft.com/en-us/windows"
    - "https://www.apple.com/iphone/"
    - "https://www.netflix.com/browse"
    - "https://github.com/open-telemetry"
    - "https://github.com/features/actions"
    - "https://github.com/login"
    - "https://www.naver.com/"
    - "https://mail.naver.com/"
    - "https://search.daum.net/search?w=tot&q=오늘의+날씨"
    - "https://www.coupang.com/vp/products/123456789"
    - "https://www.tistory.com/category/IT"
    - "https://www.kurly.com/goods/5068333"
    - "https://www.musinsa.com/app/goods/2107421"
    - "https://www.11st.co.kr/products/3456812345"
    - "https://api.github.com/users/octocat/repos"
    - "https://api.github.com/repos/open-telemetry/opentelemetry-go/issues?state=open"
    - "https://api.stripe.com/v1/charges"
    - "https://api.stripe.com/v1/customers/cus_H_12345"
    - "https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA"
    - "https://api.service.io/v2/items?page=2&per_page=50"
    - "https://api.example.com/api/v1/users/123/profile"
    - "https://api.example.com/api/v1/products?category=electronics&sort=price_desc"
    - "https://kauth.kakao.com/oauth/token"
    - "https://nid.naver.com/oauth2.0/token?grant_type=authorization_code"
    - "http://service.internal/healthz"
    - "http://10.0.1.15:8080/api/status"
    - "http://localhost:3000/graphql"
    - "https://storage.googleapis.com/my-bucket/images/photo.jpg"
    - "https://s3.ap-northeast-2.amazonaws.com/my-assets/videos/intro.mp4"
    - "https://d39kf7f6a7h32.cloudfront.net/js/app.1a2b3c4d.js"
    - "https://d39kf7f6a7h32.cloudfront.net/css/main.5e6f7g8h.css"
    - "https://user-images.githubusercontent.com/12345/67890.png"
    - "https://static.xx.fbcdn.net/rsrc.php/v3/y_/r/_pORLCa2x3d.js"
    - "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
    - "https://example.com/orders/12345"
    - "https://example.com/products/a7a43e4f-f217-4340-a35c-51b2f4d6c4d8"
    - "https://service.com/users/987/posts/45"
    - "https://myapp.com/api/v3/carts/b9e3a6c9-04a7-478a-a5ec-a3e9c63a9254/items"
    - "https://example.com/search?q=test&page=3&sort=asc#results"
    - "https://example.com/analytics/report?start_date=2025-07-01&end_date=2025-07-11&format=csv&filter=active_users"
    - "https://example.com/login/callback?code=xyz123&state=abc456"
    - "https://example.com/app/dashboard#section-3"
    - "https://docs.example.com/api/v2?version=2.1&lang=en#authentication"
    - "www.youtube.com"
    - "www.google.com"
    - "https://"
    - "https://[::1]:8080/path" # IPv6
    - "https://www.reddit.com/r/programming/"
    - "https://www.nytimes.com/2025/07/11/technology/artificial-intelligence.html"
    - "https://stackoverflow.com/questions/tagged/opentelemetry"
    - "https://medium.com/@opentelemetry"
    - "https://slack.com/apps/A01B2C3D4E5"
    - "https://zoom.us/j/1234567890"
    - "https://www.dropbox.com/sh/a1b2c3d4e5f6g7/AABBCCDDEEFF?dl=0"
    - "https://notion.so/my-workspace/My-Awesome-Page-a1b2c3d4e5f64a9b8c7d6e5f4a3b2c1d"
    - "https://sentry.io/organizations/my-org/issues/"
    - "https://grafana.com/docs/grafana/latest/"
    - "https://www.youtube.com/watch?v=Abc123Def45"
    - "https://api.github.com/orgs/opentelemetry/members"
    - "https://www.amazon.com/dp/B09XYZABCDE"
    - "https://example.com/articles/2025/07/tech-trends"
    - "https://api.service.io/v2/items?page=3&per_page=50"
    - "https://www.coupang.com/vp/products/987654321"
    - "https://github.com/search?q=opentelemetry&type=repositories"
    - "https://en.wikipedia.org/wiki/Distributed_tracing"
    - "https://api.example.com/api/v2/users/456/settings"
    - "https://www.naver.com/news/12345.html"
    - "https://s3.ap-northeast-2.amazonaws.com/my-logs/2025/07/11/app.log"
    - "https://example.com/promo?campaign=summer_sale&source=email"
  exception_types:
    crash:
      - "crash-exception-type 이다ㅏㅏㅏㅏ"
      - "crash-exception-type 일껄ㄹㄹㄹㄹㄹㄹㄹ"
      - "crash-exception-type 입니다만ㄴㄴ"
      - "crash-exception-type 인데???"
      - "crash-exception-type 일꺼임ㅁㅁㅁㅁㅁㅁㅁㅁㅁ"
      - "crash-exception-type 인가보다ㅏㅏ아아아아"
      - "crash-exception-type 인가봐ㅏㅏㅏ"
    anr:
      - "anr-except-type 이구만ㄴ..."
      - "anr-except-type 일까ㅏㅏㅏ??"
      - "anr-except-type 인건가ㅏㅏㅏㅏㅏㅏㅏㅏ"
    error:
      - "error-except-type 이지 말입니다"
      - "error-except-type 인걸까ㅏㅏㅏ"
      - "error-except-type 이지 않을깎ㄲㄲㄲ"
      - "error-except-type 이란다다다다다"
      - "error-except-type 이잖아ㅏㅏ"
  exception_messages:
    crash:
      - "crash-except-message 하이"
      - "crash-except-message 헬로"
      - "crash-except-message 안녕"
      - "crash-except-message 방가"
    anr:
      - "anr-except-message 곤니찌와"
      - "anr-except-message 봉쥬르"
      - "anr-except-message 곤방와"
    error:
      - "error-exception-message 귀"
      - "error-exception-message 찮"
      - "error-exception-message 다"
  exception_stack_traces:
    crash:
      - "crash-stack-trace 하나다!!"
      - "crash-stack-trace 둘이다!!"
      - "crash-stack-trace 셋이다!!"
    anr:
      - "anr-stack-trace ㄱㄷ!!"
      - "anr-stack-trace ㅈㅁ!!"
      - "anr-stack-trace ㄱㄱ!!"
    error:
      - "error-stack-trace 원!!"
      - "error-stack-trace 투!!"
      - "error-stack-trace 쓰리!!"
