collector_url: "http://localhost:4318"
#collector_url: "http://192.168.0.81:4318" # 현정
#collector_url: "http://192.168.0.158:4318" # 다영

go_routine_count: 200
user_count: 150

services:
  # ios
#  - name: "ios1"
#    version: "1.0.1"
#    key: "service-key"
#    type: "ios"
  - name: "ios1"
    version: "1.0.0"
    key: "service-key"
    type: "ios"
#  - name: "ios1"
#    version: "1.0.2"
#    key: "service-key"
#    type: "ios"
#  - name: "ios2"
#    version: "1.0.11"
#    key: "service-key"
#    type: "ios"
  # android
#  - name: "and1"
#    version: "1.3.5"
#    key: "service-key"
#    type: "android"
#  - name: "and1"
#    version: "2.1.1"
#    key: "service-key"
#    type: "android"
#  - name: "and2"
#    version: "2.1.1"
#    key: "service-key"
#    type: "android"
#  - name: "and3"
#    version: "1.0.4"
#    key: "service-key"
#    type: "android"
##   web
#  - name: "test-service-web-1"
#    version: "3.0.11"
#    key: "service-key"
#    type: "web"
#  - name: "test-service-web-1"
#    version: "3.0.12"
#    key: "service-key"
#    type: "web"
#  - name: "test-service-web-1"
#    version: "3.2.1"
#    key: "service-key"
#    type: "web"

span_attribute:
  screen_names:
    android:
      - "MainActivity"
      - "android-test-screen-name-1"
      - "android-test-screen-name-2"
      - "android-test-screen-name-3"
    ios:
      - "ios-test-screen-name-1"
      - "ios-test-screen-name-2"
      - "ios-test-screen-name-3"
    web:
      - "web-test-screen-name-1"
      - "web-test-screen-name-2"
      - "web-test-screen-name-3"
  http_urls:
    - "https://www.google.com/"
    - "https://www.google.com/search?q=otlp+exporter&oq=otlp"
    - "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    - "https://www.youtube.com/feed/subscriptions"
    - "https://www.amazon.com/s?k=laptop&ref=nb_sb_noss"
    - "https://www.amazon.com/gp/product/B08N5T6CZ6/"
    - "https://en.wikipedia.org/wiki/OpenTelemetry"
    - "https://en.wikipedia.org/wiki/Main_Page"
    - "https://twitter.com/home"
    - "https://twitter.com/explore"
    - "https://www.instagram.com/p/Cyzqr0oyRk_/"
    - "https://www.linkedin.com/feed/"
    - "https://www.microsoft.com/en-us/windows"
    - "https://www.apple.com/iphone/"
    - "https://www.netflix.com/browse"
    - "https://github.com/open-telemetry"
    - "https://github.com/features/actions"
    - "https://github.com/login"
    - "https://www.naver.com/"
    - "https://mail.naver.com/"
    - "https://search.daum.net/search?w=tot&q=오늘의+날씨"
    - "https://www.coupang.com/vp/products/123456789"
    - "https://www.tistory.com/category/IT"
    - "https://www.kurly.com/goods/5068333"
    - "https://www.musinsa.com/app/goods/2107421"
    - "https://www.11st.co.kr/products/3456812345"
    - "https://api.github.com/users/octocat/repos"
    - "https://api.github.com/repos/open-telemetry/opentelemetry-go/issues?state=open"
    - "https://api.stripe.com/v1/charges"
    - "https://api.stripe.com/v1/customers/cus_H_12345"
    - "https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA"
    - "https://api.service.io/v2/items?page=2&per_page=50"
    - "https://api.example.com/api/v1/users/123/profile"
    - "https://api.example.com/api/v1/products?category=electronics&sort=price_desc"
    - "https://kauth.kakao.com/oauth/token"
    - "https://nid.naver.com/oauth2.0/token?grant_type=authorization_code"
    - "http://service.internal/healthz"
    - "http://10.0.1.15:8080/api/status"
    - "http://localhost:3000/graphql"
    - "https://storage.googleapis.com/my-bucket/images/photo.jpg"
    - "https://s3.ap-northeast-2.amazonaws.com/my-assets/videos/intro.mp4"
    - "https://d39kf7f6a7h32.cloudfront.net/js/app.1a2b3c4d.js"
    - "https://d39kf7f6a7h32.cloudfront.net/css/main.5e6f7g8h.css"
    - "https://user-images.githubusercontent.com/12345/67890.png"
    - "https://static.xx.fbcdn.net/rsrc.php/v3/y_/r/_pORLCa2x3d.js"
    - "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
    - "https://example.com/orders/12345"
    - "https://example.com/products/a7a43e4f-f217-4340-a35c-51b2f4d6c4d8"
    - "https://service.com/users/987/posts/45"
    - "https://myapp.com/api/v3/carts/b9e3a6c9-04a7-478a-a5ec-a3e9c63a9254/items"
    - "https://example.com/search?q=test&page=3&sort=asc#results"
    - "https://example.com/analytics/report?start_date=2025-07-01&end_date=2025-07-11&format=csv&filter=active_users"
    - "https://example.com/login/callback?code=xyz123&state=abc456"
    - "https://example.com/app/dashboard#section-3"
    - "https://docs.example.com/api/v2?version=2.1&lang=en#authentication"
    - "www.youtube.com"
    - "www.google.com" # 스키마 없음
    - "https://" # 호스트 없음
    - "https://[::1]:8080/path" # IPv6
    - "https://www.reddit.com/r/programming/"
    - "https://www.nytimes.com/2025/07/11/technology/artificial-intelligence.html"
    - "https://stackoverflow.com/questions/tagged/opentelemetry"
    - "https://medium.com/@opentelemetry"
    - "https://slack.com/apps/A01B2C3D4E5"
    - "https://zoom.us/j/1234567890"
    - "https://www.dropbox.com/sh/a1b2c3d4e5f6g7/AABBCCDDEEFF?dl=0"
    - "https://notion.so/my-workspace/My-Awesome-Page-a1b2c3d4e5f64a9b8c7d6e5f4a3b2c1d"
    - "https://sentry.io/organizations/my-org/issues/"
    - "https://grafana.com/docs/grafana/latest/"
    - "https://www.youtube.com/watch?v=Abc123Def45"
    - "https://api.github.com/orgs/opentelemetry/members"
    - "https://www.amazon.com/dp/B09XYZABCDE"
    - "https://example.com/articles/2025/07/tech-trends"
    - "https://api.service.io/v2/items?page=3&per_page=50"
    - "https://www.coupang.com/vp/products/987654321"
    - "https://github.com/search?q=opentelemetry&type=repositories"
    - "https://en.wikipedia.org/wiki/Distributed_tracing"
    - "https://api.example.com/api/v2/users/456/settings"
    - "https://www.naver.com/news/12345.html"
    - "https://s3.ap-northeast-2.amazonaws.com/my-logs/2025/07/11/app.log"
    - "https://example.com/promo?campaign=summer_sale&source=email"
  exception_types:
    - "11-exception-type"
    - "22-exception-type"
    - "33-exception-type"
    - "44-exception-type"
    - "55-exception-type"
    - "66-exception-type"
    - "77-exception-type"
    - "88-exception-type"
    - "99-exception-type"
  exception_messages:
    - "0000-exception-message"
    - "1111-exception-message"
    - "2222-exception-message"
    - "3333-exception-message"
    - "4444-exception-message"
    - "5555-exception-message"
    - "6666-exception-message"
    - "7777-exception-message"
    - "8888-exception-message"
    - "9999-exception-message"
    - "AAAA-exception-message"
    - "BBBB-exception-message"
    - "CCCC-exception-message"
    - "DDDD-exception-message"
    - "EEEE-exception-message"
    - "FFFF-exception-message"
  exception_stack_traces:
    - "test-stack-trace 다!!"
    - "이거는 test-stack-trace 다!!"
    - "요것도 test-stack-trace 다!!"
