go_routine_count: 10

collector_url: "http://localhost:4318"

user_count: 10

services:
  # ios
  - name: "test-service-ios-1"
    version: "1.0.1"
    key: "service-key"
    platform: "ios"
  - name: "test-service-ios-1"
    version: "1.0.0"
    key: "service-key"
    platform: "ios"
  - name: "test-service-ios-1"
    version: "1.0.2"
    key: "service-key"
    platform: "ios"
  - name: "test-service-ios-2"
    version: "1.0.11"
    key: "service-key"
    platform: "ios"
  # android
  - name: "test-service-android-1"
    version: "1.3.5"
    key: "service-key"
    platform: "android"
  - name: "test-service-android-1"
    version: "2.1.1"
    key: "service-key"
    platform: "android"
  - name: "test-service-android-2"
    version: "2.1.1"
    key: "service-key"
    platform: "android"
  - name: "test-service-android-3"
    version: "1.0.4"
    key: "service-key"
    platform: "android"
  # web
  - name: "test-service-web-1"
    version: "3.0.11"
    key: "service-key"
    platform: "web"
  - name: "test-service-web-1"
    version: "3.0.12"
    key: "service-key"
    platform: "web"
  - name: "test-service-web-2"
    version: "3.2.1"
    key: "service-key"
    platform: "web"

span_attribute:
  screen_names:
    android:
      - "MainActivity"
      - "android-test-screen-name-1"
      - "android-test-screen-name-2"
      - "android-test-screen-name-3"
    ios:
      - "ios-test-screen-name-1"
      - "ios-test-screen-name-2"
      - "ios-test-screen-name-3"
    web:
      - "web-test-screen-name-1"
      - "web-test-screen-name-2"
      - "web-test-screen-name-3"
  http_urls:
    - "www.google.com"
    - "www.github.com"
    - "www.naver.com"
